export const BibleFactDB = [
  {
    _id: "fact_001",
    title: "God Made Everything!",
    fact: "In just six days, God created the entire world!",
    image: "https://yourcdn.com/fact-creation.png",
  },
  {
    _id: "fact_002",
    title: "The Bible Has 66 Books!",
    fact: "The Bible is made up of 66 books—39 in the Old Testament and 27 in the New!",
    image: "https://yourcdn.com/fact-books.png",
  },
  {
    _id: "fact_003",
    title: "Jesus Walked on Water!",
    fact: "Jesus once walked on water to reach His disciples during a storm!",
    image: "https://yourcdn.com/fact-water.png",
  },
  {
    _id: "fact_004",
    title: "The Longest Chapter!",
    fact: "Psalm 119 is the longest chapter in the Bible with 176 verses!",
    image: "https://yourcdn.com/fact-psalm119.png",
  },
  {
    _id: "fact_005",
    title: "The Shortest Verse!",
    fact: "The shortest verse in the Bible is 'Jesus wept.' (John 11:35)",
    image: "https://yourcdn.com/fact-shortest.png",
  },
  {
    _id: "fact_006",
    title: "A Talking Donkey!",
    fact: "In the Bible, God made a donkey speak to Balaam! (Numbers 22:28)",
    image: "https://yourcdn.com/fact-donkey.png",
  },
  {
    _id: "fact_007",
    title: "First Man and Woman!",
    fact: "Adam and Eve were the first people God created.",
    image: "https://yourcdn.com/fact-adam-eve.png",
  },
  {
    _id: "fact_008",
    title: "Jesus Fed Thousands!",
    fact: "With just 5 loaves and 2 fish, Jesus fed over 5,000 people!",
    image: "https://yourcdn.com/fact-loaves.png",
  },
  {
    _id: "fact_009",
    title: "The Bible Was Written Over 1,500 Years!",
    fact: "It took more than 1,500 years and 40 authors to write the Bible!",
    image: "https://yourcdn.com/fact-years.png",
  },
  {
    _id: "fact_010",
    title: "Heaven Has Streets of Gold!",
    fact: "The Bible says Heaven has streets made of pure gold! (Revelation 21:21)",
    image: "https://yourcdn.com/fact-gold.png",
  },
  {
    _id: "fact_011",
    title: "Noah’s Ark Was Huge!",
    fact: "Noah’s Ark was about 450 feet long — that's longer than a football field!",
    image: "https://yourcdn.com/fact-ark.png",
  },
  {
    _id: "fact_012",
    title: "God Gave the Ten Commandments!",
    fact: "God gave Moses the Ten Commandments on Mount Sinai.",
    image: "https://yourcdn.com/fact-ten-commandments.png",
  },
  {
    _id: "fact_013",
    title: "A Boy Became King!",
    fact: "Josiah became king of Judah when he was only 8 years old! (2 Kings 22:1)",
    image: "https://yourcdn.com/fact-josiah.png",
  },
  {
    _id: "fact_014",
    title: "A Big Fish Swallowed Jonah!",
    fact: "Jonah was in the belly of a big fish for 3 days and 3 nights!",
    image: "https://yourcdn.com/fact-jonah.png",
  },
  {
    _id: "fact_015",
    title: "God Gave Manna from Heaven!",
    fact: "God fed the Israelites in the desert with special food called manna.",
    image: "https://yourcdn.com/fact-manna.png",
  },
  {
    _id: "fact_016",
    title: "Jesus Was Born in a Manger!",
    fact: "When Jesus was born, there was no room in the inn, so He was laid in a manger.",
    image: "https://yourcdn.com/fact-manger.png",
  },
  {
    _id: "fact_017",
    title: "The Bible Was First Printed in 1455!",
    fact: "The first printed Bible was made by Johannes Gutenberg in 1455.",
    image: "https://yourcdn.com/fact-printing.png",
  },
  {
    _id: "fact_018",
    title: "There Are Over 5,000 Manuscripts!",
    fact: "There are more than 5,000 ancient Greek manuscripts of the New Testament.",
    image: "https://yourcdn.com/fact-manuscript.png",
  },
  {
    _id: "fact_019",
    title: "God Gave Us a Rainbow!",
    fact: "God gave the rainbow as a promise to never flood the whole earth again. (Genesis 9:13)",
    image: "https://yourcdn.com/fact-rainbow.png",
  },
  {
    _id: "fact_020",
    title: "Jesus Rose from the Dead!",
    fact: "Jesus rose from the grave on the third day after His crucifixion!",
    image: "https://yourcdn.com/fact-resurrection.png",
  },
];
